version: '3.1'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: ashutosh
      MYSQL_PASSWORD: ashu1234
      MYSQL_RANDOM_ROOT_PASSWORD: pass1234
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - my-net

  wordpress:
    image: wordpress:5.7.1-fpm-alpine
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=ashutosh
      - WORDPRESS_DB_PASSWORD=ashu1234
      - WORDPRESS_DB_NAME=wordpressdb
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - my-net

  nginx-web:
    image: nginx:1.20.0-alpine
    container_name: nginx-web
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network